### ISSUE TITLE
What is accumulator and why is it a dependency? Does it work on chef-solo?

### ISSUE THREAD

**Issue by budlight** [spheromak/sysctl-cookbook#8]
I'm mainly making an issue because this is the most starred recipe of its kind.  I think its fine if you want to use some obscure recipe, but might want to warn users if it won't work with chef-solo.  I personally tried quite a bit to get this setup working.  I could have just used a template much faster than trying to get this working.

**Comment by spheromak** [comment]
Accumulator is a means of collecting many resources and merging them into a single template in a single write.  It's not obscure, and should work with solo. If you could submit a proper ticket explaining the issue you hit on solo I would be more than happy to help. 

Why accumulator?

  When I originally wrote this. RHEL/CentOS 4/5 did not support  /etc/sysctl.d/*.conf  style files. So I had to generate a single file. I walked the chef resource_collection and pulled all resources of the sysctl type then generated a template from all of their settings and wrote the file. This would happen each time the sysctl resource took the `:write` action. So if you have 100 sysctl resource then that's 100 writes to the config file. 

@kisoku Wrote the accumulator lib after using this cook and realizing that these writes were happening. His cookbook solves the many resources -> 1 file  writer problem in an abstract way. I use it so that we can handle that situation.
